name: CI-CD
on:
    push:
        branches: ["main"]
    workflow_dispatch:
jobs:
    CI:
        runs-on: ubuntu-latest
        steps:
          - name: Obtendo Código
            uses: actions/checkout@v4.1.5
          - name: Autenticação Docker Hub
            uses: docker/login-action@v3.1.0
            with:
                username: ${{ secrets.DOCKERHUB_USERNAME }}
                password: ${{ secrets.DOCKERHUB_TOKEN }}
          - name: Build Imagem Docker
            uses: docker/build-push-action@v6
            with:
              context: ./src
              file: ./src/Dockerfile
              push: true
              tags: |
               caiovturco/aula-primeira-pipeline:v${{ github.run_number }}
               caiovturco/aula-primeira-pipeline:latest
    CD:
      runs-on: ubuntu-latest
      needs: [CI]
      steps:
          - name: Obtendo Código
            uses: actions/checkout@v4.1.5
          - name: Config de contexto de K8S
            uses: azure/k8s-set-context@v4
            with:
              method: kubeconfig
              kubeconfig: ${{ secrets.K8S_CONFIG }}
          - name: Deploy Aplicação
            uses: Azure/k8s-deploy@v5
            with:
              manifests: |
                  ./k8s/deployment.yaml
              images: |
                caiovturco/aula-primeira-pipeline:v${{ github.run_number }}

            
